name: PigRestaurant
options:
  bundleIdPrefix: com.xiaduan
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  PigRestaurant:
    type: application
    platform: [iOS, macOS]
    sources:
      - PigRestaurant
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xiaduan.pigrestaurant
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "猪咪餐厅"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.food-and-drink"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
